version: "1.0"
info:
  model: int-scaffold
packages:
- name: Test1306Project
  gitServerName: pt
  gitUrl: https://github.com/Pratibha0224
  gitUsername: Pratibha0224
  gitBranch: main
services:
- serviceName: project.test1306.integrations:gcd
  packages:
  - name: Test1306Project
    version: "1.0"
- serviceName: pub.date:getCurrentDate
  packages:
  - name: WmPublic
    version: 11.1.0.0.2066
